# Description:
#   None
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot beer me - Grab me a beer
#
# Author:
#  houndbee

told= [
	"[X] Told",
	"[X] Really Told",
	"[X] TOLDASAURUS REX",
	"[X] Cash4Told.com",
	"[X] No Country for Told Men",
	"[X] Knights of the Told Republic",
	"[X] ToldSpice",
	"[X] The Elder Tolds IV: Oblivious",
	"[X] Command & Conquer: Toldberian Sun",
	"[X] GuiTold Hero: World Told",
	"[X] Told King of Boletaria",
	"[X] Countold Strike",
	"[X] Unreal Toldament",
	"[X] Stone-told Steve Austin",
	"[X] Half Life 2: Episode Told",
	"[X] Roller Coaster Toldcoon",
	"[X] Assassin’s Creed: Tolderhood",
	"[X] Battletolds",
	"[X] S.T.A.L.K.E.R.: Shatold of Chernobyl",
	"[X] Toldasauraus Rex 2: Electric Toldaloo",
	"[X] Told of Duty 4: Modern Toldfare",
	"[X] Pokemon Told and Silver",
	"[X] The Legend of Eldorado : The Lost City of Told",
	"[X] Rampage: Toldal Destruction",
	"[X] Told Fortress Classic",
	"[X] Toldman: Arkham Told",
	"[X] The Good, The Bad, and The Told",
	"[X] Super Mario SunTold",
	"[X] Legend of Zelda: Toldacarnia of Time",
	"[X] Toldstone Creamery",
	"[X] Mario Golf: Toldstool Tour",
	"[X] Super Told Boy",
	"[X] Sir Barristan the Told",
	"[X] Left 4 Told",
	"[X] Battoldfield: Bad Company 2",
	"[X] Toldman Sachs",
	"[X] Conker’s Bad Fur Day: Live and Retolded",
	"[X] Lead and Told: Gangs of the Wild West",
	"[X] Portold 2",
	"[X] Avatold: The Last Airbender",
	"[X] Dragon Ball Z Toldkaichi Budokai",
	"[X] Toldcraft II: Tolds of Toldberty",
	"[X] Leo Toldstoy",
	"[X] Metal Gear Toldid 3: Snake Eater",
	"[X] 3D Dot Told Heroes",
	"[X] J.R.R Toldkien’s Lord of the Told",
	"[X] Told you that PS3 has no games",
	"[X] LitTOLD Big Planet",
	"[X] Rome: Toldal War",
	"[X] Gran Toldrismo 5",
	"[X] Told Calibur 4",
	"[X] Told Fortress 2",
	"[X] Castlevania: RonTold of Blood",
	"[X] Guilty Gear XX Accent Told",
	"[X] Cyndaquil, Chicorita, and Toldodile",
	"[X] Was foretold",
	"[X] Demon’s Told",
	"[X] http://www.youtold.com",
	"[X] Tolden Sun: Dark Dawn",
	"[X] Tic-Tac-Told",
	"[X] Biotold 2",
	"[X] Toldbound",
	"[X] Icetold",
	"[X] Told of the Rings",
	"[X] Hisoutentoldu",
	"[X] Told dish of revenge served",
	"[X] Apply told water to burnt area",
	"[X] The Tolden Rule",
	"[X] Dark Tolds",
	"[X] Told Story",
	"[X] Tolden Axe",
	"[X] Gary Toldman",
	"[X] Told MacDonald Had a Farm",
	"[X] Super Told XLVIII",
	"[X] Told Finger",
	"[X] Toldeneye",
	"[X] Told and Tolder",
	"[X] Told and Tolder Told",
	"[X] Lord Toldermort",
	"[X] Told Bond: Medicated Powder",
	"[X] The Tolder Scrolls",
	"[X] House Toldgaryan",
	"[X] Toldèmon O/P",
	"[X] Told Testament",
	"[X] World of Toldcraft: The Burning Told",
	"[X] All Told Everything",
	"[X] JRR Toldkien",
	"[X] Reddit Told",
	"[X] Told's spaghetti",
	"[X] The Toldman Show",
	"[X] Mementold",
	"[X] Toldega Nights: The Ballad of Ricky Toldy Battold Royale",
	"[X] I'll have the toldalini Alfredo, please",
	"[X] The Big Letoldski",
	"[X] Tolddock Saints",
	"[X] Legend of Total Toldage",
	"[X] carved into a toldem pole",
	"[X] DIS NIGGA GOT TOLD",
	"[X] Told-finger death punch",
	"[X] Told alexandra",
	"[X] Bring me the told",
	"[X] toldboy and the tolden army",
	"[X] Followed the tolden brick road",
	"[X] Fear and Loathing in Told Vegas",
	"[X] Told Mountain",
	"[X] Snoop told",
	"[X] Toldclub",
	"[X] The Told and the Textless",
	"[X] Tolden Caulfield",
	"[X] Told ",
	"[ ] Still Not Told",
	"[X] J.R.R Toldkien's Told of the Told",
	"[X] Land Before Told",
	"[X] The Elder Tolds III: Toldwind",
	"[X] Nightmare on Told Street",
	"[X] Bennie and the Tolds",
	"[X] David Coppertold",
	"[X] A Tale of Two Tolds",
	"[X] Colgate Toldal",
	"[X] Halftold 3",
	"[X] Egg, I dreamed I was told.",
	"[X] Gladness men of told.",
	"[X] Toldtanic",
	"[X] Dwarf Toldtress",
	"[X] www.facetold.com",
	"[X] /r/asktoldit",
	"[X] Of Tolds and men",
	"[X] The Tolder Express",
	"[X] Toldlet",
	"[X] Toldaria",
	"[X] Toldbox 360?"
]

module.exports = (robot) ->
    robot.hear /.*(how told)|btfo.*/i, (msg) ->
        msg.send "[ ] Not Told\r\n" + msg.random told